### ISSUE TITLE
publishing on app store

### ISSUE THREAD

**Issue by ptgms** [rasmuslos/music#2]
hey there :)
Im about to buy myself a developer license off apple
if you want, you can publish your app with it.
just let me know - thought id throw it out there coz this app looks cool as hell. i always disliked finamp as it looks weird

**Comment by rasmuslos** [comment]
Hey,
thanks for the offer, but I actually indent to publish the app on the App Store myself. It will sadly take some time, about two months, but it will happen, so stay tuned!

As a fair warning, I will probably put a price tag on it, something like 6 bucks, for one to pay the costs for the developer program, and because I invested quite some time into developing the app.
This does not mean that I will make the app closed source, the code will continue to be freely available, the same goes for updates

**Comment by ptgms** [comment]
I'd make it 4.99$ - a 5er is way less mental strain to buy and looks better imo.
Also - if you advertise this on jellyfin and selfhosting reddits, you're sure to get positive feedback and purchases. The app is **already** ahead of other jellyfin clients on iOS :D 
Been enjoying it a lot! Only negative I noticed is stutter or slowdowns when expanding the player

**Comment by rasmuslos** [comment]
Thanks! I didn't notice stuttering, but I can look into it

**Comment by jankuca** [comment]
Hello, any progress on the publishing? I will gladly pay for it.

**Comment by rasmuslos** [comment]
Thanks a lot! After a long back and forth between me and the Apple review team that invoked questions like how they can locate the background audio feature they actually approved the app yesterday. I have to clear some things with my tax councillor first (I live in Germany so may have to pay VAT, etc.) but I am optimistic that the release is going to come soon
